name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job-matrix:
    name: ${{ matrix.make.name }} (${{ matrix.rust }}; ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        rust:
          - nightly
          - stable
          - 1.51.0  # MSRV
        make:
          - name: format
            task: format
          - name: lint
            task: lint
          - name: test
            task: build test
          - name: doc
            task: doc
          - name: codecov
            task: lcov
            install-grcov: true
          - name: os-less-build
            task: os-less-build
            rust-free: true  # Rust is installed inside task
        exclude:
          - rust: nightly
            make:
              name: format
          - rust: 1.51.0
            make:
              name: format
          - rust: nightly
            make:
              name: lint
          - rust: 1.51.0
            make:
              name: lint
          - rust: nightly
            make:
              name: doc
          - rust: 1.51.0
            make:
              name: doc
          - rust: stable
            make:
              name: codecov
          - rust: 1.51.0
            make:
              name: codecov
    env:
      RUST_BACKTRACE: full
      CACHE_RESET_KEY: 20210611-01
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.rust }}
        if: ${{ ! matrix.make.rust-free }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: rustfmt, clippy, llvm-tools-preview
          override: true

      - name: Cache cargo registry
        if: ${{ ! matrix.make.rust-free }}
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-cargo-${{ matrix.make.name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-cargo-${{ matrix.make.name }}-
            ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-cargo-

      - name: Install cargo-make
        env:
          BASE_URL: https://github.com/sagiegurari/cargo-make/releases/download
          CARGO_MAKE_VERSION: 0.33.0
        run: |
          CARGO_MAKE_FILE_BASE=cargo-make-v${CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl
          mkdir -p ${HOME}/.local/bin
          curl -L "${BASE_URL}/${CARGO_MAKE_VERSION}/${CARGO_MAKE_FILE_BASE}.zip" --output /tmp/cargo-make.zip
          unzip /tmp/cargo-make.zip -d /tmp/cargo-make
          mv -f /tmp/cargo-make/${CARGO_MAKE_FILE_BASE}/cargo-make $HOME/.local/bin/cargo-make
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install grcov
        if: ${{ matrix.make.install-grcov }}
        env:
          BASE_URL: https://github.com/mozilla/grcov/releases/download
          GRCOV_VERSION: 0.8.0
        run: |
          GRCOV_FILE_BASE=grcov-linux-x86_64
          curl -L "${BASE_URL}/v${GRCOV_VERSION}/${GRCOV_FILE_BASE}.tar.bz2" --output /tmp/grcov.tar.bz2
          tar xvf /tmp/grcov.tar.bz2 --directory=$HOME/.local/bin/
          grcov --version

      - name: ${{ matrix.make.name }}
        run: |
          for task in ${{ matrix.make.task }} ; do
            cargo make ${task}
          done

      - name: Upload lcov to codecov
        if: ${{ matrix.install-grcov }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          files: ./lcov.info
