name: release

on:
  push:
    tags:
      - '*'

jobs:
  release-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cargo-make
        env:
          BASE_URL: https://github.com/sagiegurari/cargo-make/releases/download
          CARGO_MAKE_VERSION: 0.33.0
        run: |
          CARGO_MAKE_FILE_BASE=cargo-make-v${CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl
          mkdir -p ${HOME}/.local/bin
          curl -L "${BASE_URL}/${CARGO_MAKE_VERSION}/${CARGO_MAKE_FILE_BASE}.zip" --output /tmp/cargo-make.zip
          unzip /tmp/cargo-make.zip -d /tmp/cargo-make
          mv -f /tmp/cargo-make/${CARGO_MAKE_FILE_BASE}/cargo-make $HOME/.local/bin/cargo-make
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Git tag vs crate version
        run: cargo make check-version

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: publish cargo workspace crates to crate.io
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATE_IO_SECRET }}
          path: .

      - name: publish serde-encrypt-sgx to crate.io
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATE_IO_SECRET }}
          path: ./serde-encrypt-sgx
